default: &default
  adapter: postgresql
  encoding: unicode
  max_connections: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: postgres

development:
  <<: *default
  database: meteo_development

test:
  <<: *default
  database: meteo_test

production:
  primary: &primary_production
    <<: *default
    database: meteo_production
    username: meteo
    password: <%= ENV["METEO_DATABASE_PASSWORD"] %>
  cache:
    <<: *primary_production
    database: meteo_production_cache
    migrations_paths: db/cache_migrate
  queue:
    <<: *primary_production
    database: meteo_production_queue
    migrations_paths: db/queue_migrate
  cable:
    <<: *primary_production
    database: meteo_production_cable
    migrations_paths: db/cable_migrate
