default: &default
  adapter: postgresql
  encoding: unicode
  max_connections: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: postgres

development:
  <<: *default
  database: meteo_development

test:
  <<: *default
  database: meteo_test

production:
  primary: &primary_production
    <<: *default
    url: <%= ENV["DATABASE_URL"] %>
  cable:
    <<: *primary_production
    database: meteo_production_cable
    migrations_paths: db/cable_migrate
